-- Post-migration catalog and data-integrity verification.
--
-- Required psql variables:
--   expected_database  Database name selected by the operator.
--   expected_role      Exact login role expected for this verification run.
--   target_schema      curio_prod, curio_dev, or curio_test_<run-id>.

\set ON_ERROR_STOP on

\if :{?expected_database}
\else
\echo 'missing psql variable: expected_database'
\quit
\endif
\if :{?expected_role}
\else
\echo 'missing psql variable: expected_role'
\quit
\endif
\if :{?target_schema}
\else
\echo 'missing psql variable: target_schema'
\quit
\endif

SELECT pg_catalog.set_config('curio.verify.expected_database', :'expected_database', false);
SELECT pg_catalog.set_config('curio.verify.expected_role', :'expected_role', false);
SELECT pg_catalog.set_config('curio.verify.target_schema', :'target_schema', false);

DO $verify$
DECLARE
    schema_name text := pg_catalog.current_setting('curio.verify.target_schema');
    expected_tables constant text[] := ARRAY[
        '_sqlx_migrations',
        'users',
        'conversations',
        'messages',
        'calendar_events',
        'tasks',
        'sqlite_import_manifests'
    ];
    missing_objects text[];
    unknown_objects text[];
BEGIN
    IF schema_name <> 'curio_prod'
        AND schema_name <> 'curio_dev'
        AND schema_name !~ '^curio_test_[a-z0-9_]+$'
    THEN
        RAISE EXCEPTION 'refusing unrecognized target schema %', schema_name;
    END IF;

    IF pg_catalog.current_database()
        <> pg_catalog.current_setting('curio.verify.expected_database')
    THEN
        RAISE EXCEPTION 'connected to unexpected database %', pg_catalog.current_database();
    END IF;

    IF current_user <> pg_catalog.current_setting('curio.verify.expected_role')
    THEN
        RAISE EXCEPTION 'connected as unexpected role %', current_user;
    END IF;

    IF pg_catalog.to_regnamespace(schema_name) IS NULL THEN
        RAISE EXCEPTION 'target schema % does not exist', schema_name;
    END IF;

    SELECT pg_catalog.array_agg(expected_object ORDER BY expected_object)
    INTO missing_objects
    FROM pg_catalog.unnest(expected_tables) AS expected(expected_object)
    WHERE pg_catalog.to_regclass(pg_catalog.format('%I.%I', schema_name, expected_object)) IS NULL;

    IF missing_objects IS NOT NULL THEN
        RAISE EXCEPTION 'target schema is missing required tables: %', missing_objects;
    END IF;

    SELECT pg_catalog.array_agg(class.relname ORDER BY class.relname)
    INTO unknown_objects
    FROM pg_catalog.pg_class AS class
    JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid = class.relnamespace
    WHERE namespace.nspname = schema_name
      AND class.relkind IN ('r', 'p', 'v', 'm', 'f')
      AND class.relname <> ALL (expected_tables);

    IF unknown_objects IS NOT NULL THEN
        RAISE EXCEPTION 'target schema contains unknown table-like objects: %', unknown_objects;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM pg_catalog.pg_constraint AS constraint_record
        JOIN pg_catalog.pg_namespace AS namespace
          ON namespace.oid = constraint_record.connamespace
        WHERE namespace.nspname = schema_name
          AND NOT constraint_record.convalidated
    ) THEN
        RAISE EXCEPTION 'target schema contains unvalidated constraints';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_catalog.pg_attribute AS attribute
        JOIN pg_catalog.pg_class AS class ON class.oid = attribute.attrelid
        JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid = class.relnamespace
        WHERE namespace.nspname = schema_name
          AND class.relname = 'messages'
          AND attribute.attname = 'sort_order'
          AND attribute.attidentity = 'd'
          AND pg_catalog.format_type(attribute.atttypid, attribute.atttypmod) = 'bigint'
    ) THEN
        RAISE EXCEPTION 'messages.sort_order is not a bigint GENERATED BY DEFAULT identity';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_catalog.pg_attribute AS attribute
        JOIN pg_catalog.pg_class AS class ON class.oid = attribute.attrelid
        JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid = class.relnamespace
        WHERE namespace.nspname = schema_name
          AND class.relname = 'calendar_events'
          AND attribute.attname = 'all_day'
          AND pg_catalog.format_type(attribute.atttypid, attribute.atttypmod) = 'boolean'
    ) THEN
        RAISE EXCEPTION 'calendar_events.all_day is not boolean';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_catalog.pg_attribute AS attribute
        JOIN pg_catalog.pg_class AS class ON class.oid = attribute.attrelid
        JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid = class.relnamespace
        WHERE namespace.nspname = schema_name
          AND class.relname = 'tasks'
          AND attribute.attname = 'active'
          AND pg_catalog.format_type(attribute.atttypid, attribute.atttypmod) = 'boolean'
    ) THEN
        RAISE EXCEPTION 'tasks.active is not boolean';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_catalog.pg_attribute AS attribute
        JOIN pg_catalog.pg_class AS class ON class.oid = attribute.attrelid
        JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid = class.relnamespace
        WHERE namespace.nspname = schema_name
          AND class.relname = 'tasks'
          AND attribute.attname IN ('set_at', 'due_at')
          AND pg_catalog.format_type(attribute.atttypid, attribute.atttypmod)
              = 'timestamp(3) with time zone'
        GROUP BY class.oid
        HAVING pg_catalog.count(*) = 2
    ) THEN
        RAISE EXCEPTION 'tasks set_at/due_at columns are not timestamptz(3)';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_catalog.pg_attribute AS attribute
        JOIN pg_catalog.pg_class AS class ON class.oid = attribute.attrelid
        JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid = class.relnamespace
        WHERE namespace.nspname = schema_name
          AND class.relname = 'messages'
          AND attribute.attname = 'created_at'
          AND pg_catalog.format_type(attribute.atttypid, attribute.atttypmod)
              = 'timestamp(3) with time zone'
    ) THEN
        RAISE EXCEPTION 'messages.created_at is not timestamptz(3)';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_catalog.pg_class AS migrations
        JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid = migrations.relnamespace
        JOIN pg_catalog.pg_attribute AS version_column ON version_column.attrelid = migrations.oid
        WHERE namespace.nspname = schema_name
          AND migrations.relname = '_sqlx_migrations'
          AND version_column.attname = 'version'
    ) THEN
        RAISE EXCEPTION 'SQLx migration metadata is unavailable';
    END IF;
END
$verify$;

SELECT pg_catalog.set_config(
    'search_path',
    pg_catalog.format('%I, pg_catalog', pg_catalog.current_setting('curio.verify.target_schema')),
    false
);

SELECT
    pg_catalog.current_database() AS current_database,
    current_user AS current_user,
    pg_catalog.current_schema() AS current_schema,
    pg_catalog.current_setting('server_version') AS server_version,
    pg_catalog.current_setting('TimeZone') AS timezone,
    pg_catalog.has_schema_privilege(current_user, pg_catalog.current_schema(), 'USAGE') AS has_usage,
    pg_catalog.has_schema_privilege(current_user, pg_catalog.current_schema(), 'CREATE') AS has_create;

DO $migration$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM _sqlx_migrations
        WHERE version = 202608310002
          AND success
    ) THEN
        RAISE EXCEPTION 'required SQLx migration 202608310002 is not successful';
    END IF;
END
$migration$;

SELECT
    version,
    description,
    installed_on,
    success,
    execution_time
FROM _sqlx_migrations
ORDER BY version;

SELECT 'calendar_events' AS table_name, pg_catalog.count(*)::bigint AS row_count
FROM calendar_events
UNION ALL
SELECT 'conversations', pg_catalog.count(*)::bigint FROM conversations
UNION ALL
SELECT 'messages', pg_catalog.count(*)::bigint FROM messages
UNION ALL
SELECT 'tasks', pg_catalog.count(*)::bigint FROM tasks
UNION ALL
SELECT 'users', pg_catalog.count(*)::bigint FROM users
ORDER BY table_name;

SELECT 'messages_without_conversation' AS check_name, pg_catalog.count(*)::bigint AS violation_count
FROM messages AS message
LEFT JOIN conversations AS conversation ON conversation.id = message.conversation_id
WHERE conversation.id IS NULL
UNION ALL
SELECT 'calendar_events_without_user', pg_catalog.count(*)::bigint
FROM calendar_events AS event
LEFT JOIN users AS app_user ON app_user.id = event.user_id
WHERE app_user.id IS NULL
UNION ALL
SELECT 'tasks_without_user', pg_catalog.count(*)::bigint
FROM tasks AS task
LEFT JOIN users AS app_user ON app_user.id = task.user_id
WHERE app_user.id IS NULL
UNION ALL
SELECT 'invalid_message_role', pg_catalog.count(*)::bigint
FROM messages
WHERE role NOT IN ('user', 'assistant')
UNION ALL
SELECT 'invalid_message_status', pg_catalog.count(*)::bigint
FROM messages
WHERE status NOT IN ('pending', 'completed', 'failed', 'interrupted')
UNION ALL
SELECT 'invalid_calendar_status', pg_catalog.count(*)::bigint
FROM calendar_events
WHERE status IS NOT NULL
  AND status NOT IN ('scheduled', 'in-progress', 'blocked', 'done', 'cancelled')
UNION ALL
SELECT 'invalid_calendar_priority', pg_catalog.count(*)::bigint
FROM calendar_events
WHERE priority IS NOT NULL
  AND priority NOT IN ('low', 'medium', 'high')
UNION ALL
SELECT 'invalid_task_status', pg_catalog.count(*)::bigint
FROM tasks
WHERE status NOT IN ('scheduled', 'in-progress', 'blocked', 'done', 'cancelled')
UNION ALL
SELECT 'invalid_task_priority', pg_catalog.count(*)::bigint
FROM tasks
WHERE priority IS NOT NULL
  AND priority NOT IN ('low', 'medium', 'high')
UNION ALL
SELECT 'invalid_task_due_time', pg_catalog.count(*)::bigint
FROM tasks
WHERE due_at IS NOT NULL
  AND due_at < set_at
ORDER BY check_name;

SELECT
    table_name,
    constraint_name,
    constraint_type,
    is_deferrable,
    initially_deferred
FROM information_schema.table_constraints
WHERE table_schema = pg_catalog.current_schema()
ORDER BY table_name, constraint_name;

SELECT
    tablename,
    indexname,
    indexdef
FROM pg_catalog.pg_indexes
WHERE schemaname = pg_catalog.current_schema()
ORDER BY tablename, indexname;

SELECT
    source_sha256,
    completed_at,
    importer_version,
    importer_commit,
    users_count,
    conversations_count,
    messages_count,
    calendar_events_count
FROM sqlite_import_manifests
ORDER BY completed_at, source_sha256;
