CREATE TABLE users (
    id text PRIMARY KEY,
    name text NOT NULL,
    email text NOT NULL,
    avatar_url text,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);

CREATE UNIQUE INDEX users_email_idx ON users (email);

CREATE TABLE conversations (
    id text PRIMARY KEY,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);

CREATE TABLE messages (
    id text PRIMARY KEY,
    conversation_id text NOT NULL,
    role text NOT NULL,
    content text NOT NULL,
    status text NOT NULL,
    response_id text,
    error_code text,
    sort_order bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT messages_conversation_fk
        FOREIGN KEY (conversation_id)
        REFERENCES conversations (id)
        ON DELETE CASCADE,
    CONSTRAINT messages_role_check
        CHECK (role IN ('user', 'assistant')),
    CONSTRAINT messages_status_check
        CHECK (status IN ('pending', 'completed', 'failed', 'interrupted')),
    CONSTRAINT messages_sort_order_key UNIQUE (sort_order)
);

CREATE INDEX messages_conversation_created_idx
    ON messages (conversation_id, created_at, sort_order);

CREATE TABLE calendar_events (
    id text PRIMARY KEY,
    user_id text NOT NULL,
    title text NOT NULL,
    description text,
    status text,
    priority text,
    all_day boolean NOT NULL DEFAULT false,
    -- Keep these strings unchanged because date-only and timestamp values have
    -- distinct meanings in the public API.
    start_date text NOT NULL,
    end_date text,
    -- Normalized half-open UTC instants used only for range queries.
    starts_at timestamptz(3) NOT NULL,
    ends_at timestamptz(3) NOT NULL,
    created_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT calendar_events_user_fk
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,
    CONSTRAINT calendar_events_status_check
        CHECK (
            status IS NULL
            OR status IN ('scheduled', 'in-progress', 'blocked', 'done', 'cancelled')
        ),
    CONSTRAINT calendar_events_priority_check
        CHECK (priority IS NULL OR priority IN ('low', 'medium', 'high')),
    CONSTRAINT calendar_events_interval_check
        CHECK (starts_at < ends_at)
);

CREATE INDEX calendar_events_range_idx
    ON calendar_events (user_id, starts_at, ends_at);

-- This table intentionally stores only redacted provenance and aggregate
-- counts. Source paths, connection strings, credentials, and row content do
-- not belong in an import manifest.
CREATE TABLE sqlite_import_manifests (
    source_sha256 text PRIMARY KEY,
    completed_at timestamptz(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    importer_version text NOT NULL,
    importer_commit text NOT NULL,
    users_count bigint NOT NULL,
    conversations_count bigint NOT NULL,
    messages_count bigint NOT NULL,
    calendar_events_count bigint NOT NULL,
    CONSTRAINT sqlite_import_manifests_source_sha256_check
        CHECK (source_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT sqlite_import_manifests_users_count_check
        CHECK (users_count >= 0),
    CONSTRAINT sqlite_import_manifests_conversations_count_check
        CHECK (conversations_count >= 0),
    CONSTRAINT sqlite_import_manifests_messages_count_check
        CHECK (messages_count >= 0),
    CONSTRAINT sqlite_import_manifests_calendar_events_count_check
        CHECK (calendar_events_count >= 0)
);
